circuit:
  distances:
  - 3
  - 5
  - 7
  inital_state: '0'
  observable: Z
  order: 0p
  qec_rounds:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  special_parameter: {}
  type: steane
decoder:
  type: ml
noise_model:
  noise_rates:
  - 0.001
  - 0.0021134890398366475
  - 0.0044668359215096305
  - 0.009440608762859235
  - 0.0199526231496888
  special_parameter: {}
  type: circ
sampling:
  num_shots: 10000
